### ISSUE TITLE
Index error while running cifar10 script

### ISSUE THREAD

**Issue by tobegit3hub** [melodyguan/enas#1]
We got the error while running the `cifar10_micro_final.sh` with `TensorFlow 1.6`.

```
bash scripts/cifar10_micro_final.sh

......


Build train graph
Layer  0: Tensor("child/layer_0/final_combine/concat:0", shape=(?, 180, 32, 32), dtype=float32)
Layer  1: Tensor("child/layer_1/final_combine/concat:0", shape=(?, 180, 32, 32), dtype=float32)
Layer  2: Tensor("child/layer_2/final_combine/concat:0", shape=(?, 180, 32, 32), dtype=float32)
Layer  3: Tensor("child/layer_3/final_combine/concat:0", shape=(?, 180, 32, 32), dtype=float32)
Layer  4: Tensor("child/layer_4/final_combine/concat:0", shape=(?, 180, 32, 32), dtype=float32)
Traceback (most recent call last):
  File "src/cifar10/main.py", line 359, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/cifar10/main.py", line 355, in main
    train()
  File "src/cifar10/main.py", line 223, in train
    ops = get_ops(images, labels)
  File "src/cifar10/main.py", line 190, in get_ops
    child_model.connect_controller(None)
  File "/Users/tobe/code/enas/src/cifar10/micro_child.py", line 819, in connect_controller
    self._build_train()
  File "/Users/tobe/code/enas/src/cifar10/micro_child.py", line 702, in _build_train
    logits = self._model(self.x_train, is_training=True)
  File "/Users/tobe/code/enas/src/cifar10/micro_child.py", line 283, in _model
    normal_or_reduction_cell="reduction")
  File "/Users/tobe/code/enas/src/cifar10/micro_child.py", line 430, in _fixed_layer
    x_id = arc[4 * cell_id]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by hyhieu** [comment]
We ran the script on our local machine and didn't have this problem.

We suspect that some shell interpreters would mistake `$fixed_arc`, so perhaps changing it into a more explicit form, i.e. `${fixed_arc}` would resolve the issue. We fixed the script to reflect this change.

**Comment by tobegit3hub** [comment]
Great work and thanks for your replying @hyhieu .

It works for `TensorFlow 1.4+` now.
