### ISSUE TITLE
ValueError: Unknown search_for macro

### ISSUE THREAD

**Issue by zxydi1992** [melodyguan/enas#3]
Hi, 

When to try to run: /scripts/cifar10_macro_search.sh. I got the below exception:

Traceback (most recent call last):
  File "src/cifar10/main.py", line 359, in <module>
    tf.app.run()
  File "/home/***/.envs/py27/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/cifar10/main.py", line 355, in main
    train()
  File "src/cifar10/main.py", line 223, in train
    ops = get_ops(images, labels)
  File "src/cifar10/main.py", line 169, in get_ops
    num_replicas=FLAGS.controller_num_replicas)
  File "/home/***/Downloads/enas/src/cifar10/general_controller.py", line 81, in __init__
    self._build_sampler()
  File "/home/***/Downloads/enas/src/cifar10/general_controller.py", line 163, in _build_sampler
    raise ValueError("Unknown search_for {}".format(self.search_for))
ValueError: Unknown search_for macro

I am with Ubuntu 14.04, Python 2.7 and Tensorflow 1.3.0.

**Comment by hyhieu** [comment]
Thanks for spotting this out. The error has been fixed.

**Comment by rifaadev** [comment]
@zxydi1992 @hyhieu Hi, how you solved this I have same error ?
