### ISSUE TITLE
ValueError: Incompatible shapes between op input and calculated input gradient. 

### ISSUE THREAD

**Issue by nikdnaik** [melodyguan/enas#4]
While running the "cifar10_macro_search.sh" script, I get the following error. Is it related to the tensorflow version? I am  using 1.6.0.
================
Build train graph
Tensor("child/layer_0/case/cond/Merge:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_1/skip/bn/Identity:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_2/skip/bn/Identity:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_3/pool_at_3/from_4/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_4/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_5/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_6/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_7/pool_at_7/from_8/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_8/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_9/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_10/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_11/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Model has 697860 params
Traceback (most recent call last):
  File "src/cifar10/main.py", line 359, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/cifar10/main.py", line 355, in main
    train()
  File "src/cifar10/main.py", line 223, in train
    ops = get_ops(images, labels)
  File "src/cifar10/main.py", line 171, in get_ops
    child_model.connect_controller(controller_model)
  File "/home/nikhil/google_enas/src/cifar10/general_child.py", line 705, in connect_controller
    self._build_train()
  File "/home/nikhil/google_enas/src/cifar10/general_child.py", line 633, in _build_train
    num_replicas=self.num_replicas)
  File "/home/nikhil/google_enas/src/utils.py", line 125, in get_train_ops
    grads = tf.gradients(loss, tf_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 641, in gradients
    (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: child/layer_11/case/cond/cond/cond/cond/cond/cond/Merge.  Input index: 0. Original input shape: ().  Calculated input gradient shape: (?, 36, 8, 8)

**Comment by hyhieu** [comment]
Thanks for noting this.

We just re-ran the script and didn't see the issue. We use TensorFlow 1.4.1 though.

We'll update to 1.7 soon and let you know if we have the problem.

**Comment by nikdnaik** [comment]
Thanks for the response. I suspect that it is related to this open bug tensorflow 1.5.0 onwards: https://github.com/tensorflow/tensorflow/issues/15214

**Comment by ahundt** [comment]
I'm also on 1.7, and I've been able to reproduce this error.

**Comment by ahundt** [comment]
@hyhieu @melodyguan sorry to bug you but would it be possible to give this a try? I'm unable to run the cifar10 model search due to this issue.

**Comment by hyhieu** [comment]
Hi @ahundt. We tried running the scripts, on TF 1.4, and didn't have this problem. We have heard of this version discrepancy issue. We'll fix it, but it will take a while.

**Comment by ahundt** [comment]
Yeah I had read the rest of this issue, I was just confirming it on 1.7. I'm able to start micro search without issue (haven't completed a full run yet) which calls the same function.

Here is the macro search error I get: 
[error.txt](https://github.com/melodyguan/enas/files/1925179/error.txt)

**Comment by AbelardLiu** [comment]
I guess that this problem is caused by the tensor 
”child/layer_11/case/cond/cond/cond/cond/cond/cond/Constant“ has the shape () which is from the follow code
`out = tf.case(branches, default=lambda: tf.constant(0, tf.float32), exclusive=True)`
 I change this line into the following can run enas. 
`out = tf.case(branches, default=lambda: tf.constant(0, tf.float32, shape=[self.batch_size, out_filters, inp_h, inp_w]),  exclusive=True)`
But this change only support data-format which is "NCHW".

**Comment by ahundt** [comment]
@AbelardLiu Awesome! That gave me the info I needed to create a proper fix which should work in all cases, see https://github.com/melodyguan/enas/pull/29

**Comment by AbelardLiu** [comment]
@ahundt Great!I'll merge this commit and test,  
Btw, do you run enas use python2 or python3?
Thansks!

**Comment by ahundt** [comment]
I run on python2

**Comment by harewei** [comment]
By the way, I'm using Python3.6.5 with TensorFlow 1.7.0, and the fix by @ahundt does indeed fix this issue.

**Comment by shiyongde** [comment]
the same bug whith Tensorflow 1.8 cuda9.1 

Build train graph
Tensor("child/layer_0/case/cond/Merge:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_1/skip/bn/Identity:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_2/skip/bn/Identity:0", shape=(?, 36, 32, 32), dtype=float32)
Tensor("child/layer_3/pool_at_3/from_4/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_4/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_5/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_6/skip/bn/Identity:0", shape=(?, 36, 16, 16), dtype=float32)
Tensor("child/layer_7/pool_at_7/from_8/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_8/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_9/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_10/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Tensor("child/layer_11/skip/bn/Identity:0", shape=(?, 36, 8, 8), dtype=float32)
Model has 697860 params
Traceback (most recent call last):
  File "src/cifar10/main.py", line 359, in <module>
    tf.app.run()
  File "/data5/xiawei/program/python2/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "src/cifar10/main.py", line 355, in main
    train()
  File "src/cifar10/main.py", line 223, in train
    ops = get_ops(images, labels)
  File "src/cifar10/main.py", line 171, in get_ops
    child_model.connect_controller(controller_model)
  File "/data3/xiawei/work/enas/enas/src/cifar10/general_child.py", line 705, in connect_controller
    self._build_train()
  File "/data3/xiawei/work/enas/enas/src/cifar10/general_child.py", line 633, in _build_train
    num_replicas=self.num_replicas)
  File "/data3/xiawei/work/enas/enas/src/utils.py", line 125, in get_train_ops
    grads = tf.gradients(loss, tf_variables)
  File "/data5/xiawei/program/python2/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/data5/xiawei/program/python2/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 669, in _GradientsHelper
    (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: child/layer_11/case/cond/cond/cond/cond/cond/cond/Merge.  Input index: 0. Original input shape: ().  Calculated input gradient shape: (?, 36, 8, 8)

**Comment by upwindflys** [comment]
@AbelardLiu Thanks a lot,Fix works for me.But why out.set_shape does not work,I feel confused.

**Comment by pingguokiller** [comment]
> @AbelardLiu Thanks a lot,Fix works for me.But why out.set_shape does not work,I feel confused.

Use the code below is OK on tf1.13.
out = tf.reshape(out, (-1, inp_h, inp_w, out_filters))

"tensor.set_shape" is just to set the static shape. At most situations, we should use "tf.reshape" to set the dynamic shape.

**Comment by wangluyao123456** [comment]
> 我猜这个问题是由张量
> “ child / layer_11 / case / cond / cond / cond / cond / cond / cond / Constant”引起的，其形状为（），它来自以下代码，
> `out = tf.case(branches, default=lambda: tf.constant(0, tf.float32), exclusive=True)`
> 我将此行更改为以下代码运行enas。
> `out = tf.case(branches, default=lambda: tf.constant(0, tf.float32, shape=[self.batch_size, out_filters, inp_h, inp_w]), exclusive=True)`
> 但是此更改仅支持数据格式为“ NCHW”。

I also encountered the same problem, but when it appeared in the case of deconvolution, can you help me solve it? I am grateful.

**Comment by wangluyao123456** [comment]
我也遇到了同样的问题，但是在反卷积的情况下出现时，您能帮我解决吗？我很感激。
ValueError: Incompatible shapes between op input and calculated input gradient. Forward operation: Decoder/conv3d_transpose. Input index: 2. Original input shape: (20, 2, 16, 1, 1). Calculated input gradient shape: (20, 3, 16, 8, 1)
与tf.variable_scope（'Decoder'）一起使用：
print（'self.masked_v'，self.masked_v.get_shape（））
vector_j = tf.reshape（self.masked_v，shape =（cfg.batch_size，2，16，1， 1））
kernel2 = tf.constant（1.0，shape = [3，3，2，1，1]）＃反向卷积核
kernel3 = tf.constant（1.0，shape = [3，1，29，1， 1]）＃反向卷积核
deconv11 = tf.nn.conv3d_transpose（vector_j，kernel2，output_shape = [cfg.batch_size，3，16，18，1]，步幅= [1、2、2、2、1 
] ，padding =“ SAME”）
print（'deconv1'，deconv11.get_shape（））

**Comment by maryam089** [comment]
@ahundt I'm using Python3.6 with TensorFlow 1.5.1 and my issue is 
[Report Error]ValueError: Incompatible shapes between op input and calculated input gradient. conv2d_transpose
any idea how to solve it ?

**Comment by maryam089** [comment]
The problem has been solved. The issue was with the strides

**Comment by laksheenmendis** [comment]
I also got the same issue with Python 3.7 with TensorFlow 1.15.2, and the fix by @ahundt (https://github.com/melodyguan/enas/pull/29) fixed the issue. And I believe it should be merged to the master branch for future users (I spent a lot of time on this issue)
