### ISSUE TITLE
Error while running macro search for cifar 10

### ISSUE THREAD

**Issue by ManasiPat** [melodyguan/enas#73]
I am getting the following error after running the script cfar10_macro_search. sh:
Starting session
2018-10-10 19:20:31.254266: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-10 19:20:31.254292: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-10 19:20:31.254298: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-10-10 19:20:31.254304: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-10 19:20:31.254309: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-10-10 19:20:31.345224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-10-10 19:20:31.345741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: Quadro M1000M
major: 5 minor: 0 memoryClockRate (GHz) 1.0715
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.63GiB
2018-10-10 19:20:31.345760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-10-10 19:20:31.345767: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-10-10 19:20:31.345776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0)
2018-10-10 19:20:36.730060: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2170 get requests, put_count=1200 evicted_count=1000 eviction_rate=0.833333 and unsatisfied allocation rate=0.953917
2018-10-10 19:20:36.730096: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl_lite.cc:164] **Cannot allocate buffer larger than kint32max for StringOutputStream.**
Traceback (most recent call last):
  File "src/cifar10/main.py", line 359, in <module>
    tf.app.run()
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "src/cifar10/main.py", line 355, in main
    train()
  File "src/cifar10/main.py", line 253, in train
    loss, lr, gn, tr_acc, _ = sess.run(run_ops)
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 944, in run
    feed_dict, options)
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 970, in _call_hook_before_run
    request = hook.before_run(run_context)
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 353, in before_run
    "graph.pbtxt")
  File "/home/manasi/anaconda2/envs/ENAS/lib/python2.7/site-packages/tensorflow/python/framework/graph_io.py", line 67, in write_graph
    file_io.atomic_write_string_to_file(path, str(graph_def))
ValueError: Unable to convert message to str
The highlighted statement indicates there is something wrong with the memory allocation by GPU.
My GPU has 4 GB memory. Can somebody help me solve the issue. Thanks

**Comment by imhgchoi** [comment]
I'm also having the same problem :<

**Comment by myepsilon** [comment]
I'm the same. Does anyone know how to solve this?

**Comment by nott0** [comment]
I guess that this is because you have not enough GPU memories. Maybe you search for a network model that is too large ( too many layers or number of filters). Or maybe your batch size is too large.

**Comment by imhgchoi** [comment]
But I'm working on the same GPU mentioned in the paper. I'm still getting the errors
