### ISSUE TITLE
ENAS child model creation error

### ISSUE THREAD

**Issue by samra-irshad** [melodyguan/enas#89]
Could anyone point why is this error happening?

``
Tensor("child/layer_0/final_conv/Relu:0", shape=(?, 32, 32, 36), dtype=float32)
Tensor("child/layer_1/skip/bn/Identity:0", shape=(?, 32, 32, 36), dtype=float32)
Tensor("child/layer_2/skip/bn/Identity:0", shape=(?, 32, 32, 36), dtype=float32)
Tensor("child/layer_3/pool_at_3/from_4/bn/Identity:0", shape=(?, 16, 16, 36), dtype=float32)
Tensor("child/layer_4/skip/bn/Identity:0", shape=(?, 16, 16, 36), dtype=float32)
Tensor("child/layer_5/skip/bn/Identity:0", shape=(?, 16, 16, 36), dtype=float32)
Tensor("child/layer_6/skip/bn/Identity:0", shape=(?, 16, 16, 36), dtype=float32)
Tensor("child/layer_7/pool_at_7/from_8/bn/Identity:0", shape=(?, 8, 8, 36), dtype=float32)
Tensor("child/layer_8/skip/bn/Identity:0", shape=(?, 8, 8, 36), dtype=float32)
Tensor("child/layer_9/skip/bn/Identity:0", shape=(?, 8, 8, 36), dtype=float32)
Tensor("child/layer_10/skip/bn/Identity:0", shape=(?, 8, 8, 36), dtype=float32)
Traceback (most recent call last):
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 5 of dimension 0 out of bounds. for 'child/layer_11/skip/strided_slice_5' (op: 'StridedSlice') with input shapes: [5], [1], [1], [1] and with computed input tensors: input[1] = <5>, input[2] = <6>, input[3] = <1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/ALIENWARE/.PyCharmCE2018.3/config/scratches/main.py", line 363, in <module>
    tf.app.run()
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Users/ALIENWARE/.PyCharmCE2018.3/config/scratches/main.py", line 359, in main
    train()
  File "C:/Users/ALIENWARE/.PyCharmCE2018.3/config/scratches/main.py", line 227, in train
    ops = get_ops(images, labels)
  File "C:/Users/ALIENWARE/.PyCharmCE2018.3/config/scratches/main.py", line 175, in get_ops
    child_model.connect_controller(controller_model)
  File "C:\Users\ALIENWARE\.PyCharmCE2018.3\config\scratches\general_child.py", line 711, in connect_controller
    self._build_train()
  File "C:\Users\ALIENWARE\.PyCharmCE2018.3\config\scratches\general_child.py", line 601, in _build_train
    logits = self._model(self.x_train, is_training=True)
  File "C:\Users\ALIENWARE\.PyCharmCE2018.3\config\scratches\general_child.py", line 209, in _model
    x = self._enas_layer(layer_id, layers, start_idx, out_filters, is_training)
  File "C:\Users\ALIENWARE\.PyCharmCE2018.3\config\scratches\general_child.py", line 368, in _enas_layer
    res_layers.append(tf.cond(tf.equal(skip[i], 1),
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 538, in _SliceHelper
    name=name)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 706, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5429, in strided_slice
File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Users\ALIENWARE\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: slice index 5 of dimension 0 out of bounds. for 'child/layer_11/skip/strided_slice_5' (op: 'StridedSlice') with input shapes: [5], [1], [1], [1] and with computed input tensors: input[1] = <5>, input[2] = <6>, input[3] = <1>.
Exception ignored in: <utils.Logger object at 0x000001F2743A7240>
AttributeError: 'Logger' object has no attribute 'flush

**Comment by chg0901** [comment]
Did you solve the problem？ I also have it now

**Comment by thunguyenth** [comment]
I solved it by adding the following function to the class Logger in file 'utils.py'
  
```
def flush(self):
    pass
```
